#!/bin/bash

cp fig-EXEDOS_traj/fig-EXEDOS_2D.pdf ../slides/figs/
cp fig-EXEDOS_traj/fig-EXEDOS_traj_3.pdf ../slides/figs/
cp fig-WLMC_all/fig-WLMC_all_Cv.pdf ../slides/figs/
cp fig-WLMC_all/fig-WLMC_all_P2.pdf ../slides/figs/
cp fig-WLMC_all/fig-WLMC_all_Q6.pdf ../slides/figs/
cp fig-WLMC_ind_plots_10p25/fig-WLMC_Cv_plain_10p25.pdf ../slides/figs/
cp fig-WL_DOS_traj/fig-WL_DOS_traj.pdf ../slides/figs/
cp fig-WL_DOS_traj/fig-WL_DOS_traj_0.pdf ../slides/figs/
cp fig-WL_DOS_traj/fig-WL_DOS_traj_1.pdf ../slides/figs/
cp fig-WL_DOS_traj/fig-WL_DOS_traj_2.pdf ../slides/figs/
cp fig-WL_DOS_traj/fig-WL_DOS_traj_3.pdf ../slides/figs/
cp fig-arrows/fig-right_arrow_text.pdf ../slides/figs/
cp fig-cryst_confs_plus_structs/fig-cryst_confs_plus_structs.pdf ../slides/figs/
cp fig-cryst_confs_plus_structs/fig-cryst_confs_plus_structs_1.pdf ../slides/figs/
cp fig-heights_vs_phi/fig-heights_vs_phi.pdf ../slides/figs/
cp fig-melt_confs_plus_structs/fig-melt_confs_plus_structs.pdf ../slides/figs/
cp fig-melt_confs_plus_structs/fig-melt_confs_plus_structs_1.pdf ../slides/figs/
cp fig-nematic_confs_plus_structs/fig-nematic_confs_plus_structs.pdf ../slides/figs/
cp fig-nematic_confs_plus_structs/fig-nematic_confs_plus_structs_1.pdf ../slides/figs/
cp fig-pathway_10p25/fig-phase_diag_mark_cryst.pdf ../slides/figs/
cp fig-pathway_10p25/subfig-2d_barrier_10p25_small.pdf ../slides/figs/
cp fig-pathway_10p25/subfig-pathway_10p25.pdf ../slides/figs/
cp fig-pathway_10p25/subfig-pathway_10p25_small.pdf ../slides/figs/
cp fig-pathway_10p25/subfig-pathway_noMFEP_10p25.pdf ../slides/figs/
cp fig-pathway_10p75/fig-phase_diag_mark_nematic.pdf ../slides/figs/
cp fig-pathway_10p75/subfig-pathway_10p75.pdf ../slides/figs/
cp fig-pathway_10p75/subfig-pathway_noMFEP_10p75.pdf ../slides/figs/
cp fig-phase_diag/fig-phase_diag.pdf ../slides/figs/
